# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preWelding.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 550)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 450, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.MClabel = QtWidgets.QLabel(Dialog)
        self.MClabel.setGeometry(QtCore.QRect(90, 80, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.MClabel.setFont(font)
        self.MClabel.setObjectName("MClabel")
        self.MClabel_2 = QtWidgets.QLabel(Dialog)
        self.MClabel_2.setGeometry(QtCore.QRect(80, 240, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.MClabel_2.setFont(font)
        self.MClabel_2.setObjectName("MClabel_2")
        self.MClabel_3 = QtWidgets.QLabel(Dialog)
        self.MClabel_3.setGeometry(QtCore.QRect(80, 330, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.MClabel_3.setFont(font)
        self.MClabel_3.setObjectName("MClabel_3")
        self.MClabel_4 = QtWidgets.QLabel(Dialog)
        self.MClabel_4.setGeometry(QtCore.QRect(90, 140, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.MClabel_4.setFont(font)
        self.MClabel_4.setObjectName("MClabel_4")
        self.MC = QtWidgets.QComboBox(Dialog)
        self.MC.setGeometry(QtCore.QRect(230, 90, 141, 22))
        self.MC.setObjectName("MC")
        self.MC.addItem("")
        self.MC.addItem("")
        self.MC.addItem("")
        self.MC.addItem("")
        self.MC.addItem("")
        self.MC.addItem("")
        self.MC.addItem("")
        self.MC.addItem("")
        self.height = QtWidgets.QLineEdit(Dialog)
        self.height.setGeometry(QtCore.QRect(230, 150, 113, 20))
        self.height.setObjectName("height")
        self.width = QtWidgets.QLineEdit(Dialog)
        self.width.setGeometry(QtCore.QRect(230, 340, 113, 20))
        self.width.setObjectName("width")
        self.JT = QtWidgets.QComboBox(Dialog)
        self.JT.setGeometry(QtCore.QRect(220, 250, 141, 22))
        self.JT.setObjectName("JT")
        self.JT.addItem("")
        self.JT.addItem("")
        self.JT.addItem("")
        self.JT.addItem("")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.MClabel.setText(_translate("Dialog", "母材种类"))
        self.MClabel_2.setText(_translate("Dialog", "接头形式"))
        self.MClabel_3.setText(_translate("Dialog", "板缝间隙"))
        self.MClabel_4.setText(_translate("Dialog", "厚度"))
        self.MC.setItemText(0, _translate("Dialog", "A级一般强度结构钢"))
        self.MC.setItemText(1, _translate("Dialog", "B级一般强度结构钢"))
        self.MC.setItemText(2, _translate("Dialog", "D级一般强度结构钢"))
        self.MC.setItemText(3, _translate("Dialog", "E级一般强度结构钢"))
        self.MC.setItemText(4, _translate("Dialog", "A级高强度结构钢"))
        self.MC.setItemText(5, _translate("Dialog", "D级高强度结构钢"))
        self.MC.setItemText(6, _translate("Dialog", "E级高强度结构钢"))
        self.MC.setItemText(7, _translate("Dialog", "F级高强度结构钢"))
        self.JT.setItemText(0, _translate("Dialog", "对接"))
        self.JT.setItemText(1, _translate("Dialog", "角接"))
        self.JT.setItemText(2, _translate("Dialog", "T型接"))
        self.JT.setItemText(3, _translate("Dialog", "搭接"))
